In [1]:
import numpy as np

def calculate_dh_matrix(theta, alpha, a, d):
    """
    Calculate the homogeneous transformation matrix using DH parameters.
    
    Args:
        theta: Joint angle in radians (rotation about z-axis)
        alpha: Link twist in radians (rotation about x-axis)
        a: Link length (translation along x-axis)
        d: Link offset (translation along z-axis)
    
    Returns:
        4x4 homogeneous transformation matrix
    """
    # Create the rotation and translation matrices
    cos_theta = np.cos(theta)
    sin_theta = np.sin(theta)
    cos_alpha = np.cos(alpha)
    sin_alpha = np.sin(alpha)
    
    # Build the homogeneous transformation matrix
    H = np.array([
        [cos_theta, -sin_theta*cos_alpha,  sin_theta*sin_alpha, a*cos_theta],
        [sin_theta,  cos_theta*cos_alpha, -cos_theta*sin_alpha, a*sin_theta],
        [0,         sin_alpha,            cos_alpha,           d],
        [0,         0,                    0,                   1]
    ])
    
    return H

In [ ]:
theta = np.pi/4  # 45 degrees
alpha = np.pi/2  # 90 degrees
a = 0.5         # 0.5 units
d = 0.3         # 0.3 units

H = calculate_dh_matrix(theta, alpha, a, d)
print("Transformation matrix:")
print(H)



Transformation matrix:
[[ 7.07106781e-01 -4.32978028e-17  7.07106781e-01  3.53553391e-01]
 [ 7.07106781e-01  4.32978028e-17 -7.07106781e-01  3.53553391e-01]
 [ 0.00000000e+00  1.00000000e+00  6.12323400e-17  3.00000000e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [2]:


H_0_to_1 = calculate_dh_matrix(theta1, 90, 0, L1)
H_1_to_2 = calculate_dh_matrix(theta2, 0, L2, 0)
H_2_to_3 = calculate_dh_matrix(theta3, 0, L3, 0)
H_3_to_4 = calculate_dh_matrix(theta4, 0, L4, 0)
H_4_to_5 = calculate_dh_matrix(theta5, 0, 0, L5)

H = H_0_to_1 * H_1_to_2 * H_2_to_3 * H_3_to_4 * H_4_to_5


NameError: name 'calculate_dh_matrix' is not defined